In [ ]:
import os
import math
import pandas as pd
import numpy as np
from pathlib import Path
import xml.dom.minidom 
from datetime import datetime, timedelta
import xml.etree.ElementTree as Et

# paga o caminho para a raiz database
def get_xml_root():
    try:
        BASE_DIR = os.path.dirname(os.path.abspath(__file__))
    except NameError:
        BASE_DIR = os.getcwd()
    return os.path.join(BASE_DIR, "..", "OhioT1DM")

# paga o caminho para os arquivos XML
def get_XMLs(root, seletor: str):
    p = Path(root)
    lista_XML = []

    for x in p.iterdir():
        if x.is_dir() :
            lista_XML.extend(get_XMLs(x, seletor))
        elif "testing" in x.name and seletor == "training": 
            continue
        elif "training" in x.name and seletor == "testing": 
            continue
        elif x.suffix == ".xml": 
            lista_XML.append(x)

    return lista_XML

# estrai as informaçõens dos XMLs
def get_info(file_XML, dados: dict):
    domtree = xml.dom.minidom.parse(str(file_XML))

    patient = domtree.documentElement
    assert patient is not None

    id_patient = int(patient.getAttribute('id'))
    
    if id_patient not in  dados.keys():
        dados[id_patient] = {}

    finger_stick = patient.getElementsByTagName('finger_stick')[0].getElementsByTagName('event')
    for event in finger_stick:
        ts =  binning(event.getAttribute('ts'))
        dados[id_patient][ts] = new_entry(ts, dados.keys(), id_patient)
        dados[id_patient][ts]["metodo_medida"] = "finger_stick"
        dados[id_patient][ts]["glucose_level"] = int(event.getAttribute('value'))

    glucose_level = patient.getElementsByTagName('glucose_level')[0].getElementsByTagName('event')
    for event in glucose_level:
        ts =  binning(event.getAttribute('ts'))
        dados[id_patient][ts] = new_entry(ts, dados.keys(), id_patient)
        dados[id_patient][ts]["metodo_medida"] = "CGM"
        dados[id_patient][ts]["glucose_level"] = int(event.getAttribute('value'))

    bolus = patient.getElementsByTagName('bolus')[0].getElementsByTagName('event')
    for event in bolus:
        ts_begin =  binning(event.getAttribute('ts_begin'))
        ts_end =  binning(event.getAttribute('ts_end'))
        ts_diferenca = (ts_end-ts_begin).total_seconds()

        dados[id_patient][ts_begin] = new_entry(ts_begin, dados.keys(), id_patient)

        if ts_diferenca == 0:
            dados[id_patient][ts_begin]["bolus_type"] = event.getAttribute('type')
            dados[id_patient][ts_begin]["bolus_dose"] += float(event.getAttribute('dose'))
        else:
            ts_between = int(ts_diferenca / 60 / 5)
            dose = float(event.getAttribute('dose'))/ts_between

            for i in range(0, ts_between+1):
                ts = ts_begin + timedelta(minutes= 5*i)
                dados[id_patient][ts] = new_entry(ts, dados.keys(), id_patient)
                dados[id_patient][ts]["bolus_type"] = event.getAttribute('type')
                dados[id_patient][ts]["bolus_dose"] += dose

    meal = patient.getElementsByTagName('meal')[0].getElementsByTagName('event')
    for event in meal:
        ts =  binning(event.getAttribute('ts'))
        dados[id_patient][ts] = new_entry(ts, dados.keys(), id_patient)
        dados[id_patient][ts]["meal_type"] = event.getAttribute('type')
        dados[id_patient][ts]["meal_carbs"] = int(event.getAttribute('carbs'))

    basal = patient.getElementsByTagName('basal')[0].getElementsByTagName('event')
    for event in basal:
        ts =  binning(event.getAttribute('ts'))

        for entry in dados[id_patient]:
            if entry >= ts:
                dados[id_patient][entry]["basal"] = float(event.getAttribute('value'))

    temp_basal = patient.getElementsByTagName('temp_basal')[0].getElementsByTagName('event')
    for event in temp_basal:
        ts_begin =  binning(event.getAttribute('ts_begin'))
        ts_end =  binning(event.getAttribute('ts_end'))

        for entry in dados[id_patient]:
            if entry >= ts_begin and entry <= ts_end:
                dados[id_patient][entry]["basal"] = float(event.getAttribute('value'))

    sleep = patient.getElementsByTagName('basis_sleep')[0].getElementsByTagName('event')
    for event in sleep:
        ts_begin =  binning(event.getAttribute('tbegin'))
        ts_end =  binning(event.getAttribute('tend'))

        for entry in dados[id_patient]:
            if ts_begin <= entry and entry <= ts_end: 
                # print(id_patient)
                # print(entry)
                # print(dados[id_patient][entry])
                dados[id_patient][entry]["sleeping"] = True
                dados[id_patient][entry]["sleep_quality"] = int(event.getAttribute('quality'))

    exercise = patient.getElementsByTagName('exercise')[0].getElementsByTagName('event')
    for event in exercise:
        ts_begin =  binning(event.getAttribute('ts'))
        ts_end = ts_begin + timedelta(minutes= int(event.getAttribute('duration')))

        for entry in dados[id_patient]:
            if entry >= ts_begin and entry <= ts_end:
                dados[id_patient][entry]["doing_exercise"] = True
                dados[id_patient][entry]["exercise_intensity"] = int(event.getAttribute('intensity'))

    for event in dados[id_patient]:
        if dados[id_patient][event]["glucose_level"] is not None:
            ts_target = event - timedelta(hours= 1)
            if ts_target in dados[id_patient].keys():
                dados[id_patient][ts_target]["target"] = dados[id_patient][event]["glucose_level"]
    
    return dados

# cria uma nova entrada caso ela não existir
def new_entry(ts, keys, id_patient):
    if ts not in keys:
        Nentry = {"id_patient": id_patient,
                    "ts": ts,
                    "metodo_medida": None, 
                    "glucose_level": None,
                    "basal": None,
                    "bolus_type": None,
                    "bolus_dose": 0,
                    "meal_type": None, 
                    "meal_carbs": None,
                    "sleeping": False,
                    "sleep_quality": None,
                    "exercise_intensity": None,
                    "doing_exercise": False,
                    "target": None}
    return Nentry

# aredonda o horario para o 5 muinutos enterior 
def binning(ts): 
    data = datetime.strptime(ts, "%d-%m-%Y %H:%M:%S")
    i = 5
    mim = data.minute//i*i
    return data.replace(minute = mim, second = 0)

def filer(df_final):
    for idx, event in df_final.iterrows():
        if pd.isna(event["glucose_level"]):
            back = 5
            past_glucose = None
            future_glucose = None
            past_weight = None
            future_weight = None

            while ((past_glucose is None) or (future_glucose is None)) and (back <= 150):
                ts_past_glucose = event["ts"] - timedelta(minutes= back)
                ts_future_glucose = event["ts"] + timedelta(minutes= back)

                if (past_glucose is None):
                    result_past = df_final.loc[
                        (df_final["ts"] == ts_past_glucose) &
                        (df_final["id_patient"] == event["id_patient"]) &
                        (df_final["glucose_level"].notna()),
                        ["glucose_level", "metodo_medida"]
                    ]
                    
                    if not result_past.empty:
                        past_glucose = result_past.iloc[0]
                        past_weight = 1 / (back / 5)

                if (future_glucose is None):
                    result_future = df_final.loc[
                        (df_final["ts"] == ts_future_glucose) &
                        (df_final["id_patient"] == event["id_patient"]) &
                        (df_final["glucose_level"].notna()),
                        ["glucose_level", "metodo_medida"]
                    ]
                    
                    if not result_future.empty:
                        future_glucose = result_future.iloc[0]
                        future_weight = 1 / (back / 5)

                if past_glucose is None or future_glucose is None:
                    back += 5
            
            if past_glucose is not None and future_glucose is not None:
                assert past_weight is not None
                assert future_weight is not None

                glucose_level = (
                    past_glucose["glucose_level"] * past_weight +
                    future_glucose["glucose_level"] * future_weight
                ) / (past_weight + future_weight)

                df_final.loc[idx, "glucose_level"] = glucose_level
                df_final.loc[idx, "metodo_medida"] = "interpolado"

            elif (past_glucose is not None):
                df_final.loc[idx, "glucose_level"] = past_glucose["glucose_level"]
                df_final.loc[idx, "metodo_medida"] = past_glucose["metodo_medida"]
                
            elif (future_glucose is not None):
                df_final.loc[idx, "glucose_level"] = future_glucose["glucose_level"]
                df_final.loc[idx, "metodo_medida"] = future_glucose["metodo_medida"]

    return df_final
    
lista_XML_training = get_XMLs(get_xml_root(), "training")
lista_XML_testing = get_XMLs(get_xml_root(), "testing")

dados_treinamento = []
for file in lista_XML_training:
    dados = {}
    dados = get_info(file, dados)

    for pacient in dados:
        for ts in dados[pacient]:
            dados_treinamento.append(dados[pacient][ts])

dados_testes = []
for file in lista_XML_testing:

    dados = {}
    dados = get_info(file, dados)

    for pacient in dados:
        for ts in dados[pacient]:
            dados_testes.append(dados[pacient][ts])


# dados_geral = []
# for pacient in dados_testes:
#     for ts in dados_testes[pacient]:
#         dados_geral.append(dados_testes[pacient][ts])
# df_paciente = pd.DataFrame(dados_geral)

df_treinamento = pd.DataFrame(dados_treinamento)
df_testes = pd.DataFrame(dados_testes)


display(df_treinamento)
display(df_testes)
# display(df_paciente)

,id_patient,ts,metodo_medida,glucose_level,basal,bolus_type,bolus_dose,meal_type,meal_carbs,sleeping,sleep_quality,exercise_intensity,doing_exercise,target
0,559,2021-12-07 01:00:00,finger_stick,107.0,0.65,NaN,0.0,NaN,NaN,False,NaN,NaN,False,145.0
1,559,2021-12-07 01:05:00,NaN,NaN,0.65,normal,1.6,NaN,NaN,False,NaN,NaN,False,148.0
2,559,2021-12-07 05:05:00,CGM,67.0,0.00,NaN,0.0,NaN,NaN,False,NaN,NaN,False,116.0
3,559,2021-12-07 11:20:00,NaN,NaN,0.90,normal,9.3,NaN,NaN,False,NaN,NaN,False,195.0
4,559,2021-12-07 12:20:00,CGM,195.0,0.90,NaN,0.0,NaN,NaN,False,NaN,NaN,False,206.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
135794,596,2027-05-24 10:15:00,NaN,NaN,0.60,NaN,0.0,Snack,15.0,False,NaN,NaN,False,NaN
135795,596,2027-05-24 12:10:00,NaN,NaN,0.60,NaN,0.0,Lunch,35.0,False,NaN,NaN,False,NaN
135796,596,2027-05-24 17:30:00,NaN,NaN,0.60,NaN,0.0,Dinner,53.0,False,NaN,NaN,False,NaN
135797,596,2027-05-24 20:50:00,NaN,NaN,0.60,NaN,0.0,Snack,12.0,False,NaN,NaN,False,NaN
135798,596,2027-05-25 06:30:00,NaN,NaN,0.60,NaN,0.0,Breakfast,27.0,False,NaN,NaN,False,208.0

,id_patient,ts,metodo_medida,glucose_level,basal,bolus_type,bolus_dose,meal_type,meal_carbs,sleeping,sleep_quality,exercise_intensity,doing_exercise,target
0,559,2022-01-18 06:25:00,NaN,NaN,1.15,normal,6.3,NaN,NaN,False,NaN,NaN,False,285.0
1,559,2022-01-18 16:55:00,CGM,150.0,0.83,NaN,0.0,NaN,NaN,False,NaN,5.0,True,NaN
2,559,2022-01-18 17:55:00,NaN,NaN,0.83,normal,0.2,NaN,NaN,False,NaN,NaN,False,183.0
3,559,2022-01-19 04:30:00,CGM,96.0,0.73,NaN,0.0,NaN,NaN,False,NaN,NaN,False,NaN
4,559,2022-01-19 05:30:00,NaN,NaN,1.15,normal,1.2,NaN,NaN,False,NaN,NaN,False,177.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
31957,596,2027-05-30 11:35:00,NaN,NaN,0.60,NaN,0.0,Lunch,41.0,False,NaN,NaN,False,NaN
31958,596,2027-05-30 14:40:00,NaN,NaN,0.60,NaN,0.0,Snack,7.0,False,NaN,NaN,False,NaN
31959,596,2027-05-30 17:25:00,NaN,NaN,0.60,NaN,0.0,Dinner,51.0,False,NaN,NaN,False,91.0
31960,596,2027-06-03 16:10:00,NaN,NaN,0.60,NaN,0.0,Snack,16.0,False,NaN,NaN,False,NaN
31961,596,2027-06-03 17:45:00,NaN,NaN,0.60,NaN,0.0,Dinner,46.0,False,NaN,NaN,False,105.0

In [8]:
display(df_treinamento.info())
display(df_testes.info())

display(df_treinamento.columns)
display(df_testes.columns)

<class 'pandas.DataFrame'>
RangeIndex: 135799 entries, 0 to 135798
Data columns (total 14 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   id_patient          135799 non-null  int64
 1   ts                  135799 non-null  datetime64[us]
 2   metodo_medida       130260 non-null  str
 3   glucose_level       130260 non-null  float64
 4   basal               135787 non-null  float64
 5   bolus_type          3750 non-null    str
 6   bolus_dose          135799 non-null  float64
 7   meal_type           1789 non-null    str
 8   meal_carbs          1789 non-null    float64
 9   sleeping            135799 non-null  bool
 10  sleep_quality       30648 non-null   float64
 11  exercise_intensity  2983 non-null    float64
 12  doing_exercise      135799 non-null  bool
 13  target              126920 non-null  float64
dtypes: bool(2), datetime64[us](1), float64(7), int64(1), str(3)
memory usage: 12.7 MB

None

<class 'pandas.DataFrame'>
RangeIndex: 31962 entries, 0 to 31961
Data columns (total 14 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   id_patient          31962 non-null  int64
 1   ts                  31962 non-null  datetime64[us]
 2   metodo_medida       30681 non-null  str
 3   glucose_level       30681 non-null  float64
 4   basal               31123 non-null  float64
 5   bolus_type          906 non-null    str
 6   bolus_dose          31962 non-null  float64
 7   meal_type           375 non-null    str
 8   meal_carbs          375 non-null    float64
 9   sleeping            31962 non-null  bool
 10  sleep_quality       7555 non-null   float64
 11  exercise_intensity  659 non-null    float64
 12  doing_exercise      31962 non-null  bool
 13  target              29812 non-null  float64
dtypes: bool(2), datetime64[us](1), float64(7), int64(1), str(3)
memory usage: 3.0 MB

None

Index(['id_patient', 'ts', 'metodo_medida', 'glucose_level', 'basal',
       'bolus_type', 'bolus_dose', 'meal_type', 'meal_carbs', 'sleeping',
       'sleep_quality', 'exercise_intensity', 'doing_exercise', 'target'],
      dtype='str')

Index(['id_patient', 'ts', 'metodo_medida', 'glucose_level', 'basal',
       'bolus_type', 'bolus_dose', 'meal_type', 'meal_carbs', 'sleeping',
       'sleep_quality', 'exercise_intensity', 'doing_exercise', 'target'],
      dtype='str')

In [11]:
df_treinamento_final = df_treinamento.sort_values(by=["id_patient", "ts"]).reset_index(drop=True)
df_testes_final = df_testes.sort_values(by=["id_patient", "ts"]).reset_index(drop=True)

df_treinamento_final = filer(df_treinamento_final)
df_testes_final = filer(df_testes_final)

display(df_treinamento_final)
display(df_testes_final)

,id_patient,ts,metodo_medida,glucose_level,basal,bolus_type,bolus_dose,meal_type,meal_carbs,sleeping,sleep_quality,exercise_intensity,doing_exercise,target
0,540,2027-05-19 07:15:00,NaN,NaN,1.05,normal,0.8,NaN,NaN,False,NaN,NaN,False,NaN
1,540,2027-05-19 11:20:00,finger_stick,80.0,0.95,NaN,0.0,NaN,NaN,False,NaN,NaN,False,99.0
2,540,2027-05-19 11:35:00,CGM,76.0,0.95,NaN,0.0,NaN,NaN,False,NaN,NaN,False,131.0
3,540,2027-05-19 11:40:00,CGM,72.0,0.95,NaN,0.0,NaN,NaN,False,NaN,NaN,False,NaN
4,540,2027-05-19 11:45:00,CGM,68.0,0.95,NaN,0.0,NaN,NaN,False,NaN,NaN,False,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
135794,596,2027-05-26 23:35:00,CGM,170.0,0.45,NaN,0.0,NaN,NaN,False,NaN,NaN,False,NaN
135795,596,2027-05-26 23:40:00,CGM,172.0,0.45,NaN,0.0,NaN,NaN,False,NaN,NaN,False,NaN
135796,596,2027-05-26 23:45:00,CGM,173.0,0.45,NaN,0.0,NaN,NaN,False,NaN,NaN,False,NaN
135797,596,2027-05-26 23:50:00,CGM,174.0,0.45,NaN,0.0,NaN,NaN,False,NaN,NaN,False,NaN
135798,596,2027-05-26 23:55:00,CGM,174.0,0.45,NaN,0.0,NaN,NaN,False,NaN,NaN,False,NaN

,id_patient,ts,metodo_medida,glucose_level,basal,bolus_type,bolus_dose,meal_type,meal_carbs,sleeping,sleep_quality,exercise_intensity,doing_exercise,target
0,540,2027-07-04 00:00:00,CGM,254.0,1.6,NaN,0.0,NaN,NaN,False,NaN,NaN,False,209.0
1,540,2027-07-04 00:05:00,CGM,250.0,1.6,NaN,0.0,NaN,NaN,False,NaN,NaN,False,205.0
2,540,2027-07-04 00:10:00,CGM,249.0,1.6,NaN,0.0,NaN,NaN,False,NaN,NaN,False,208.0
3,540,2027-07-04 00:15:00,CGM,247.0,1.6,NaN,0.0,NaN,NaN,False,NaN,NaN,False,210.0
4,540,2027-07-04 00:20:00,CGM,242.0,0.8,NaN,0.0,NaN,NaN,False,NaN,NaN,False,206.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
31957,596,2027-06-06 09:50:00,CGM,92.0,0.6,NaN,0.0,NaN,NaN,False,NaN,NaN,False,NaN
31958,596,2027-06-06 09:55:00,CGM,93.0,0.6,NaN,0.0,NaN,NaN,False,NaN,NaN,False,NaN
31959,596,2027-06-06 10:00:00,CGM,90.0,0.6,NaN,0.0,NaN,NaN,False,NaN,NaN,False,NaN
31960,596,2027-06-06 10:05:00,CGM,86.0,0.6,NaN,0.0,NaN,NaN,False,NaN,NaN,False,NaN
31961,596,2027-06-06 10:10:00,CGM,87.0,0.6,NaN,0.0,NaN,NaN,False,NaN,NaN,False,NaN

In [10]:
display(df_treinamento_final.info())
display(df_testes_final.info())

display(
    df_treinamento_final.loc[
        df_treinamento_final["metodo_medida"] == "interpolado"
    ]
)

display(
    df_testes_final.loc[
        df_testes_final["metodo_medida"] == "interpolado"
    ]
)

<class 'pandas.DataFrame'>
RangeIndex: 135799 entries, 0 to 135798
Data columns (total 14 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   id_patient          135799 non-null  int64
 1   ts                  135799 non-null  datetime64[us]
 2   metodo_medida       135690 non-null  str
 3   glucose_level       135690 non-null  float64
 4   basal               135787 non-null  float64
 5   bolus_type          3750 non-null    str
 6   bolus_dose          135799 non-null  float64
 7   meal_type           1789 non-null    str
 8   meal_carbs          1789 non-null    float64
 9   sleeping            135799 non-null  bool
 10  sleep_quality       30648 non-null   float64
 11  exercise_intensity  2983 non-null    float64
 12  doing_exercise      135799 non-null  bool
 13  target              126920 non-null  float64
dtypes: bool(2), datetime64[us](1), float64(7), int64(1), str(3)
memory usage: 12.7 MB

None

<class 'pandas.DataFrame'>
RangeIndex: 31962 entries, 0 to 31961
Data columns (total 14 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   id_patient          31962 non-null  int64
 1   ts                  31962 non-null  datetime64[us]
 2   metodo_medida       31918 non-null  str
 3   glucose_level       31918 non-null  float64
 4   basal               31123 non-null  float64
 5   bolus_type          906 non-null    str
 6   bolus_dose          31962 non-null  float64
 7   meal_type           375 non-null    str
 8   meal_carbs          375 non-null    float64
 9   sleeping            31962 non-null  bool
 10  sleep_quality       7555 non-null   float64
 11  exercise_intensity  659 non-null    float64
 12  doing_exercise      31962 non-null  bool
 13  target              29812 non-null  float64
dtypes: bool(2), datetime64[us](1), float64(7), int64(1), str(3)
memory usage: 3.0 MB

None

,id_patient,ts,metodo_medida,glucose_level,basal,bolus_type,bolus_dose,meal_type,meal_carbs,sleeping,sleep_quality,exercise_intensity,doing_exercise,target
8,540,2027-05-19 12:05:00,interpolado,72.000,0.95,normal dual,5.500000,NaN,NaN,False,NaN,NaN,False,NaN
15,540,2027-05-19 12:40:00,interpolado,130.625,1.90,square dual,0.933333,NaN,NaN,False,NaN,NaN,False,127.0
16,540,2027-05-19 12:45:00,interpolado,130.250,1.90,square dual,0.933333,NaN,NaN,False,NaN,NaN,False,124.0
17,540,2027-05-19 12:50:00,interpolado,129.875,1.90,square dual,0.933333,NaN,NaN,False,NaN,NaN,False,123.0
18,540,2027-05-19 12:55:00,interpolado,129.500,1.90,square dual,0.933333,NaN,NaN,False,NaN,NaN,False,124.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
135684,596,2027-05-26 14:25:00,interpolado,72.000,0.60,NaN,0.000000,HypoCorrection,23.0,True,0.0,NaN,False,128.0
135733,596,2027-05-26 18:30:00,interpolado,82.000,0.60,NaN,0.000000,Dinner,42.0,False,NaN,NaN,False,110.0
135734,596,2027-05-26 18:35:00,interpolado,89.000,0.60,normal,4.000000,NaN,NaN,False,NaN,NaN,False,121.0
135741,596,2027-05-26 19:10:00,interpolado,108.500,0.60,NaN,0.000000,Snack,7.0,False,NaN,NaN,False,137.0
135762,596,2027-05-26 20:55:00,interpolado,132.500,0.60,NaN,0.000000,Snack,6.0,False,NaN,NaN,False,150.0

,id_patient,ts,metodo_medida,glucose_level,basal,bolus_type,bolus_dose,meal_type,meal_carbs,sleeping,sleep_quality,exercise_intensity,doing_exercise,target
54,540,2027-07-04 04:30:00,interpolado,176.500000,0.80,normal,1.2,NaN,NaN,False,NaN,NaN,False,190.0
108,540,2027-07-04 09:00:00,interpolado,89.500000,0.95,NaN,0.0,Breakfast,40.0,False,NaN,NaN,False,142.0
113,540,2027-07-04 09:25:00,interpolado,87.000000,0.95,normal,1.8,NaN,NaN,False,NaN,NaN,False,173.0
148,540,2027-07-04 12:20:00,interpolado,83.000000,0.95,NaN,0.0,Lunch,30.0,False,NaN,NaN,False,112.0
156,540,2027-07-04 13:00:00,interpolado,76.500000,0.95,normal dual,2.7,NaN,NaN,False,NaN,NaN,False,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
31764,596,2027-06-05 17:45:00,interpolado,77.500000,0.60,normal,4.5,NaN,NaN,False,NaN,NaN,False,87.0
31767,596,2027-06-05 18:00:00,interpolado,74.000000,0.60,NaN,0.0,Dinner,55.0,False,NaN,NaN,False,98.0
31797,596,2027-06-05 20:30:00,interpolado,137.666667,0.60,normal,1.4,NaN,NaN,False,NaN,NaN,False,141.0
31798,596,2027-06-05 20:35:00,interpolado,137.333333,0.60,NaN,0.0,Snack,11.0,False,NaN,NaN,False,146.0
31903,596,2027-06-06 05:20:00,interpolado,116.000000,0.60,NaN,0.0,Breakfast,30.0,False,NaN,NaN,False,164.0